# Generated by Django 3.2.4 on 2021-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_auth_created_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='id',
        ),
        migrations.AlterField(
            model_name='auth',
            name='rdifCode',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
